export {default as Heart} from './heartIcon.png'
export {default as Home} from './homeIcon.png'
export {default as RedHeart} from './redHeart.png'
export {default as Search} from './searchIcon.png'
export {default as Inavitas} from './inavitas.png'
export {default  as Background } from './background.png'